### PR TITLE
Add support for additional webpack configuration

### PR DESCRIPTION
**Pull request by svicalifornia**
@kitze This PR adds the ability to extend the react-scripts webpack configuration with additional options, specified in a `webpack.custom-config.js` file in the app directory. See the README changes for an example using `sassLoader` options.

### CODE REVIEW

**Comment by svicalifornia** [comment]
I wrote my own merge function here so that we could concat arrays instead of replacing them, as most of the merge libraries on npm appear to do. For example, if we define `entry` in the `webpack.custom-config.js` exports object, then those externals will be appended to the `entry` elements already produced by `custom-react-scripts`, instead of replacing them.

However, in some cases it would be better to prepend elements instead of appending, or to replace arrays completely. There's not an elegant way to indicate this preference in a simple merge object, so I've considered adding support for a post-process merge function that would receive the config from `custom-react-scripts`, modify it as desired, and return the new config. The `webpack.custom-config.js` could be reused for this use case — if it exports an object, merge the object, and if it exports a function, use the function as a post-processor. That is not included in this PR, but I could work on that next week.

The merge strategy for custom config options goes one level deep. If the `webpack.custom-config.js` config export contains a `module` object, then its contents will be copied into the `module` object produced by `custom-react-scripts`. But if `webpack.custom-config.js` defines `module.loaders`, then this would completely replace the `module.loaders` from `custom-react-scripts`. I considered making the merge function redundant and would like to add that to this PR, but I'm curious to get your thoughts.

**Comment by jukben** [comment]
Looking forward to this! ❤️

**Comment by kitze** [comment]
Sorry @jukben @svicalifornia, custom webpack/babel configs won't be supported in this package. Already explained why in few opened issues, I'm also going to add that in the readme just so it's clear for other contributors in the future.

**Comment by svicalifornia** [comment]
This is important enough that if you don't support it, my company will start promoting our own fork of this package or move to another solution.

Your README does not explain your decision. I await your further explanation.

**Pull request closed without merging**
